# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Matthew-Eng-Triprise-App' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Matthew-Eng-Triprise-App
  pod 'Alamofire'
  pod 'ObjectMapper'

end
